# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Mantab3
                                 A QGIS plugin
 Map Geologis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-23
        copyright            : (C) 2020 by Map Geologis
        email                : MapGeologis@ma.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Mantab3 class from file Mantab3.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Map_Geologis import Mantab3
    return Mantab3(iface)
